# Generated by Django 4.0 on 2022-01-05 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('contract', models.CharField(choices=[('permanent', 'Permanent Contract'), ('fixed', 'Fixed-Time Contract'), ('internship', 'Internship')], default='permanent', max_length=30)),
                ('type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time')], default='full_time', max_length=30)),
                ('modalities', models.CharField(choices=[('remote', 'Remote'), ('on_site', 'On site'), ('hybrid', 'Hybrid')], default='hybrid', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('closed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='workflow.company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('in_review', 'In review'), ('waiting', 'Waiting for interview'), ('offer', 'Offer'), ('disqualified', 'Disqualified')], default='applied', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='authentication.user')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='workflow.job')),
            ],
        ),
    ]
