# Generated by Django 4.0 on 2021-12-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_alter_application_applicant_alter_application_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='attachments',
            field=models.JSONField(null=True),
        ),
    ]
