# Generated by Django 4.0 on 2022-01-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_alter_application_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='attachments',
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
